// ──────────────────────────────────────────────────────────────
// Navigation configuration — single source of truth for all modules
// ──────────────────────────────────────────────────────────────

export const NAV_ITEMS = [
  {
    id: 'flight-tracker',
    path: '/flight-tracker',
    emoji: '🛫',
    label: 'Flight Tracker',
    shortDesc: 'Track live flights across India in real-time',
    description: 'Track domestic and international flights in real time with live flight information and operational updates.',
    apiSource: 'OpenSky Network API',
    color: '#00C2FF',
    colorBg: 'rgba(0, 194, 255, 0.12)',
    colorBorder: 'rgba(0, 194, 255, 0.3)',
  },
  {
    id: 'airport-intelligence',
    path: '/airport-intelligence',
    emoji: '🏢',
    label: 'Airport Intelligence',
    shortDesc: 'Deep analytics on Indian airport operations',
    description: 'Help passengers understand airport conditions before they travel and make better travel decisions.',
    apiSource: 'OpenSky Network API',
    color: '#06EDD8',
    colorBg: 'rgba(6, 237, 216, 0.12)',
    colorBorder: 'rgba(6, 237, 216, 0.3)',
  },
  {
    id: 'ai-insights',
    label: 'TravelReady AI',
    emoji: '✈️',
    path: '/ai-insights',
    shortDesc: 'Your AI-powered international travel readiness assistant',
    description: 'Helps Indian passengers prepare for international travel with readiness scoring, country rules, and AI-generated advice.',
    apiSource: 'Neo4j + Render + Sarvam AI',
    color: '#7C3AED',
    colorBg: 'rgba(124, 58, 237, 0.12)',
    colorBorder: 'rgba(124, 58, 237, 0.3)',
  },
  {
    id: 'skygpt',
    path: '/skygpt',
    emoji: '💬',
    label: 'SkyGPT Copilot',
    shortDesc: 'AI travel assistant — ask anything in Hindi or English',
    description: 'A multilingual AI travel assistant for Indian passengers powered by Sarvam AI.',
    apiSource: 'Sarvam AI API',
    color: '#F59E0B',
    colorBg: 'rgba(245, 158, 11, 0.12)',
    colorBorder: 'rgba(245, 158, 11, 0.3)',
  },
  {
    id: 'compensation',
    path: '/compensation',
    emoji: '⚖️',
    label: 'Compensation Assistant',
    shortDesc: 'Know your rights and claim what you deserve',
    description: 'An AI-powered assistant that helps passengers understand compensation eligibility under DGCA and airline policies.',
    apiSource: 'Neo4j AuraDB',
    color: '#10B981',
    colorBg: 'rgba(16, 185, 129, 0.12)',
    colorBorder: 'rgba(16, 185, 129, 0.3)',
  },
  {
    id: 'missed-connection',
    path: '/missed-connection',
    emoji: '🔗',
    label: 'Missed Connection Predictor',
    shortDesc: 'Predict connection risk before you board',
    description: 'Predict the likelihood of missing a connecting flight using graph relationships and historical flight information.',
    apiSource: 'Neo4j AuraDB',
    color: '#F43F5E',
    colorBg: 'rgba(244, 63, 94, 0.12)',
    colorBorder: 'rgba(244, 63, 94, 0.3)',
  },
]
